require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/school_classes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SchoolClass. As you add validations to SchoolClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # SchoolClassesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      SchoolClass.create! valid_attributes
      get school_classes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      school_class = SchoolClass.create! valid_attributes
      get school_class_url(school_class), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SchoolClass" do
        expect {
          post school_classes_url,
               params: { school_class: valid_attributes }, headers: valid_headers, as: :json
        }.to change(SchoolClass, :count).by(1)
      end

      it "renders a JSON response with the new school_class" do
        post school_classes_url,
             params: { school_class: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SchoolClass" do
        expect {
          post school_classes_url,
               params: { school_class: invalid_attributes }, as: :json
        }.to change(SchoolClass, :count).by(0)
      end

      it "renders a JSON response with errors for the new school_class" do
        post school_classes_url,
             params: { school_class: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested school_class" do
        school_class = SchoolClass.create! valid_attributes
        patch school_class_url(school_class),
              params: { school_class: new_attributes }, headers: valid_headers, as: :json
        school_class.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the school_class" do
        school_class = SchoolClass.create! valid_attributes
        patch school_class_url(school_class),
              params: { school_class: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the school_class" do
        school_class = SchoolClass.create! valid_attributes
        patch school_class_url(school_class),
              params: { school_class: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested school_class" do
      school_class = SchoolClass.create! valid_attributes
      expect {
        delete school_class_url(school_class), headers: valid_headers, as: :json
      }.to change(SchoolClass, :count).by(-1)
    end
  end
end
